title: RGBoard Docs
description: A guide on how to create RGBoards and use the provided software.
theme: just-the-docs

favicon: "/assets/images/rgb-paw.png"
logo: "/assets/images/RGB-Icon.png"

url: https://just-the-docs.github.io



aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
