title: RGBoard Docs
description: A guide on how to create RGBoards and use the provided software.
theme: just-the-docs

favicon: "/assets/images/rgb-paw.png"
logo: "/assets/images/RGB-Icon.png"

url: https://https://rgboard.github.io/docs
